services:
  view-counter:
    build: ./backend
    container_name: view-counter
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend/data:/root/data
    restart: always
